# Generated by Django 2.2.9 on 2020-05-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='imagenes_producto')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_imagenes', to='products.Product')),
            ],
        ),
    ]
