# Generated by Django 2.2.9 on 2020-05-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_imagenesproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenesproducto',
            name='Description',
        ),
    ]
